### ISSUE TITLE
May I ask when the models folder can be open source and if the code is complete?

### ISSUE THREAD

**Issue by yiruzzz** [thaoshibe/edit-one-for-all#2]

**Comment by jacobmarks** [comment]
Second this! @thaoshibe the README says code will be updated in March, which I assume meant March 2024. This is super cool work, and I'd love to be able to play around with the code/models!

**Comment by TomatoBoy90** [comment]
> Second this! @thaoshibe the README says code will be updated in March, which I assume meant March 2024. This is super cool work, and I'd love to be able to play around with the code/models!

You may refer to dragan code and model, because the author did not copy the repetitive code.

**Comment by thaoshibe** [comment]
Hello, sorry for the late reply. Thank you TomatoBoy90 for correction: I did not re-train the DragGAN, so please refer to DragGAN for pretrained model: https://github.com/XingangPan/DragGAN
